english_animals_dict = {
  "Elephant": "Слон",
  "Hippopotamus": "Бегемот (гіпопотам)",
  "Rhinoceros": "Носоріг",
  "Giraffe": "Жирафа",
  "Gorilla": "Горила",
  "Bear": "Ведмідь",
  "Panda": "Панда",
  "Moose": "Лось",
  "Giant eland": "Гігантська канна (вид антилопи)",
  "Giant forest hog": "Велика лісова свиня",
  "Mammoth": "Мамонт",
  "Yak": "Як",
  "Camel": "Верблюд",
  "Gaur": "Гаур (індійський бізон)",
  "Manatee": "Ламантин",
  "Sea lion": "Морський лев",
  "Seal": "Тюлень",
  "Walrus": "Морж",
  "Boar": "Дикий кабан (вепр)",
  "Warthog": "Бородавочник",
  "Sea otter": "Морська видра (калан)",
  "Musk ox": "Мускусний бик (вівцебик)",
  "Buffalo": "Буйвол",
  "Bison": "Бізон",
  "Whale": "Кит"
}
